module.exports = {
  APP_NAME: `NZAMY`,
  PORT: process.env.APP_PORT,
  DB_URL:
    process.env.NODE_ENV == "production"
      ? process.env.PROD_DB_URL
      : process.env.DB_URL,
  LLM_MODEL: 'gpt-4o-mini',
  WEB_BASE_URL: "http://localhost:3000",
  PAGINATION_LIMIT: 10,
  SUPPORT_NUMBER: "+201555415331",
  GENDER: ["MALE", "FEMALE"],
  SOURCES: ["whatsapp", "facebook", "instagram"],
  ROLES: ["OWNER", "DOCTOR", "STAFF"],
  TYPES: ["EMPLOYEE", "ADMIN"],
  SPECIALITIES_TYPES: ["MAIN", "SUB"],
  SUBSCRIPTION_STATUS: ["PAID", "REFUNDED", "CANCELLED"],
  OPENAI_API_KEYS: process.env.OPENAI_API_KEYS,
  OPENAI_ASSISTANT_ID: process.env.OPENAI_ASSISTANT_ID,
  EMAIL: {
    APP_MAIL: "raayaeg@gmail.com",
    APP_MAIL_PASSWORD: process.env.APP_MAIL_PASSWORD,
    APP_MAIL_SERVICE: "gmail",
  },
  PAYMOB_HMAC: process.env.PAYMOB_HMAC,
  PAYMOB_API_KEYS: process.env.PAYMOB_API_KEYS,
  PAYMOB: {
    LOCAL_CARDS_INTEGRATION_ID: 3931768,
    MOBILE_WALLET_INTEGRATION_ID: 4447178,
  },
  FACEBOOK: {
    VERIFY_TOKEN: process.env.FACEBOOK_VERIFY_TOKEN,
    PAGE_ACCESS_TOKEN: process.env.FACEBOOK_PAGE_ACCESS_TOKEN,
    CLIENT_ID: process.env.FACEBOOK_CLIENT_ID,
    CLIENT_SECRET: process.env.FACEBOOK_CLIENT_SECRET,
    REDIRECT_URL: process.env.FACEBOOK_REDIRECT_URL,
    SUCCESS_URL: "http://localhost:3000/onboarding/successful-connection",
    ERROR_URL: "http://localhost:3000/onboarding/grant-permission",
  },
  SALT_ROUNDS: Number.parseInt(process.env.SALT_ROUNDS),
  SECRET_KEY: process.env.SECRET_KEY,
  NOTIFICATION_EMAIL: "omarredaelsayedmohamed@gmail.com",
  LANGUAGES: ["ENGLISH", "ARABIC"],
  PAYMENT_STATUS: ["SUCCESS", "PENDING", "FAILED", "REFUNDED"],
  STATUS_VALUES: ["PENDING", "PAID", "REFUNDED", "FAILED", "CANCELLED"],
  TIME_UNIT: ["day", "week", "month"],
  WEEK_DAYS: [
    "SUNDAY",
    "MONDAY",
    "TUESDAY",
    "WEDNESDAY",
    "THURSDAY",
    "FRIDAY",
    "SATURDAY",
  ],
  PAYMENT_METHODS: [
    "cod",
    "card",
    "bank_transfer",
    "mobile_wallet",
    "fawry",
    "vodafone_cash",
    "orange_money",
    "etisalat_cash",
    "stc_pay",
    "mada",
    "benefitpay",
    "knet",
    "omannet",
    "naps",
    "cib_smart_wallet",
    "baridpay",
    "d17",
    "paypal",
    "apple_pay",
    "google_pay",
  ],
  PERSONA_VALUES: ["FORMAL", "WITTY", "LUXURIOUS", "PROFESSIONAL"],
  RETURN_SHIPPING_PAYER_VALUES: ["CUSTOMER", "STORE", "SHARED"],
  REFUND_TYPES: [
    "ORIGINAL_PAYMENT_METHOD",
    "STORE_CREDIT",
    "BANK_TRANSFER",
    "CASH",
    "EXCHANGE_ONLY",
  ],
  RETURN_CONDITIONS: [
    "item must be unused",
    "original packaging required",
    "include receipt or proof of purchase",
    "product must be in resellable condition",
    "sealed items must be unopened",
    "return not accepted for clearance items",
    "return not accepted for custom orders",
  ],
  EGYPT_CITIES: [
    "CAIRO",
    "ALEXANDRIA",
    "GIZA",
    "DAKAHLIA",
    "RED SEA",
    "BEHEIRA",
    "FAYOUM",
    "GHARBIA",
    "ISMAILIA",
    "MENOUFIA",
    "MINYA",
    "QALYUBIA",
    "NEW VALLEY",
    "SUEZ",
    "ASWAN",
    "ASSIUT",
    "BENI SUEF",
    "PORT SAID",
    "DAMIETTA",
    "SOUTH SINAI",
    "SHARQIA",
    "KAFR El SHEIKH",
    "MATROUH",
    "LUXOR",
    "QENA",
    "NORTH SINAI",
    "SOHAG",
  ],

  STORE_CATEGORY_VALUES: [
    "FASHION",
    "BEAUTY",
    "ELECTRONICS",
    "HOME_APPLIANCES",
    "GROCERIES",
    "FURNITURE",
    "BOOKS",
    "TOYS",
    "SPORTS",
    "PHARMACY",
    "PET_SUPPLIES",
    "AUTOMOTIVE",
    "BABY_PRODUCTS",
    "JEWELRY",
    "TOOLS_HARDWARE",
  ],
  LOYALTY_TRANSACTION_TYPES: ["earn", "redeem", "expire", "adjust"],
  LOYALTY_TRANSACTION_REASONS: [
    "purchase",
    "referral",
    "review",
    "signup",
    "birthday",
    "manual_adjustment",
    "redemption",
    "expiration",
  ],
  LOYALTY_RULE_ACTION_TYPES: [
    "purchase",
    "referral",
    "review",
    "signup",
    "birthday",
  ],
  CART_STATUS: ["active", "abandoned", "converted"],
  OFFER_TYPES: ["percentage", "fixed"],
  OFFER_STATUS: ["active", "paused", "draft"],
  ORDER_STATUS: [
    "pending",
    "confirmed",
    "processing",
    "shipped",
    "delivered",
    "cancelled",
    "returned",
  ],
};
